# Shadowrocket: 2026-02-22 13:30:35
[General]
bypass-system = true
skip-proxy = 10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = 8.8.8.8
fallback-dns-server = system
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
# direct domain fail to resolve use proxy rule
dns-direct-fallback-proxy = true
# The fallback behavior when UDP traffic matches a policy that doesn't support the UDP relay. Possible values: DIRECT, REJECT.
udp-policy-not-supported-behaviour = REJECT

[Rule]
DOMAIN-KEYWORD,telegram,PROXY
IP-CIDR,149.154.166.0/23,PROXY
IP-CIDR,149.154.164.0/23,PROXY
IP-CIDR,149.154.162.0/23,PROXY
IP-CIDR,149.154.160.0/23,PROXY
IP-CIDR,149.154.164.0/22,PROXY
IP-CIDR,149.154.160.0/22,PROXY
IP-CIDR,91.108.56.0/22,PROXY
IP-CIDR,91.108.8.0/22,PROXY
IP-CIDR,91.108.4.0/22,PROXY
IP-CIDR,95.161.64.0/20,PROXY
IP-CIDR,91.105.192.0/23,PROXY
DOMAIN-KEYWORD,ytimg,PROXY
DOMAIN-KEYWORD,googlevideo,PROXY
DOMAIN-KEYWORD,whatsapp,PROXY
DOMAIN-KEYWORD,fbcdn,PROXY
DOMAIN-KEYWORD,youtube,PROXY
DOMAIN-KEYWORD,ggpht,PROXY
# LAN
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
# Final
FINAL,DIRECT

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302
