# Shadowrocket: 2026-02-22 13:30:35
[General]
bypass-system = true
skip-proxy = 10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = 94.140.14.14, 94.140.15.15
fallback-dns-server = system
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = false
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = true
udp-policy-not-supported-behaviour = REJECT
hijack-dns = :53

update-url = https://raw.githubusercontent.com/leeqveed/shadowrocket/refs/heads/main/emeraldgod.conf

[Rule]
RULE-SET,https://raw.githubusercontent.com/leeqveed/shadowrocket/refs/heads/main/voice_ports.list,PROXY
RULE-SET,https://raw.githubusercontent.com/leeqveed/shadowrocket/refs/heads/main/telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/leeqveed/shadowrocket/refs/heads/main/whatsapp.list,PROXY
RULE-SET,https://raw.githubusercontent.com/leeqveed/shadowrocket/refs/heads/main/youtube.list,PROXY
DOMAIN-SUFFIX,testdomainsuffix,PROXY

# LAN
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
# Final
FINAL,DIRECT

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302
